### ISSUE TITLE
validate on session start

### ISSUE THREAD

**Issue by bwl21** [32leaves/ruruku#53]
1. it appears that testplan.yaml is read only once, and then is persisted in ruruku.db, So I delete ruruku.db before every start

2. rururku should give messages when validateing testplan.yaml. For example it loads if "group" is an empty string. But it does not show testcases

3. ruruku should not stop if there are duplicate ids. It would be enough to raise a warning and ignore the the newer duplcates

**Comment by 32leaves** [comment]
Indeed, in ruruku the testplan only exists as a file in your source code - it's does not have a direct representation on the backend. That said, a running test session (i.e. the execution/instance of a testplan) contains the same information. Thus, if you want to "forget" your test result/test session, deleting the database file is a feasible method.

Ruruku did not do a good job at validating it's input. At least for testplans (`session start`) that's much improved with #55.

I think that ignoring testcases with a warning due to duplicate ID's would be surprising behavior, and certainly easier to overlook than a complete failure. Most of the time duplicate ID's are unintentional anyways.

**Comment by bwl21** [comment]
I disagree with #3. If duplicate ids are a problem, it then should at least give a prominent error message listing all duplicate ids. If such a prominent message exists, it does not matter if it is followed by a blank screen or by the remaining test cases.
